/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.ksnapshot.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KSNAPSHOTADAPTATOR_H_302351149509923
#define KSNAPSHOTADAPTATOR_H_302351149509923

#include <QtCore/QObject>
#include <QtCore/QMetaObject>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Adaptor class for interface org.kde.ksnapshot
 */
class KsnapshotAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.ksnapshot")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.ksnapshot\" >\n"
"    <method name=\"slotGrab\" />\n"
"    <method name=\"slotPrint\" />\n"
"    <method name=\"slotSave\" />\n"
"    <method name=\"url\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"save\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"      <arg direction=\"in\" type=\"b\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"slotSaveAs\" />\n"
"    <method name=\"slotCopy\" />\n"
"    <method name=\"setTime\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"newTime\" />\n"
"    </method>\n"
"    <method name=\"timeout\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"setURL\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"newURL\" />\n"
"    </method>\n"
"    <method name=\"setGrabMode\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"grab\" />\n"
"    </method>\n"
"    <method name=\"grabMode\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"slotMovePointer\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\" />\n"
"    </method>\n"
"    <method name=\"exit\" />\n"
"  </interface>\n"
        "")
public:
    KsnapshotAdaptor(QObject *parent);
    virtual ~KsnapshotAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void exit();
    int grabMode();
    bool save(bool filename);
    void setGrabMode(int grab);
    void setTime(int newTime);
    void setURL(const QString &newURL);
    void slotCopy();
    void slotGrab();
    void slotMovePointer(int x, int y);
    void slotPrint();
    void slotSave();
    void slotSaveAs();
    int timeout();
    QString url();
Q_SIGNALS: // SIGNALS
};

#endif
